### ISSUE TITLE
make google form for travel assistance

### ISSUE THREAD

**Issue by piamancini** [sustainers/website#69] opened 2017-04-01 12:19 UTC
@BenJam has been talking to Sloan for travel support. The process might be that we need to make a formal application to support XX tix for XX participants. A way of managing that is to add a google form on the website for people to apply for assistance with travel details.

**Comment by whit537** [comment] 2017-04-04 16:49
Closing as a dupe of https://github.com/sustainers/website/issues/32. S'okay, @piamancini? :-)

**Closed by whit537** 2017-04-04 16:49 UTC
